# Generated by Django 5.1.5 on 2025-02-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Produits laitiers, oeufs, fromages', 'Prouits Laitiers Oeufs Fromage'), ('Fruits, légumes', 'Fruits Legumes'), ('Boucherie, volaille, poissonnerie', 'Boucherie Volaille Poissonnerie'), ('Charcuterie,traiteur', 'Charcuterie Traiteur'), ('Pain, pâtisserie', 'Pain Patisserie'), ('Surgelés', 'Surgeles'), ('Epicerie,sucrée', 'Epicerie Sucree'), ('Epicerie_salée', 'Epicerie Salee'), ('Eaux,jus,soda,thès glaces', 'Eaux Jus Soda Thes Glaces'), ('Vins, bières, alcools', 'Vins Bieres Alcools'), ('Hygiène,beauté ', 'Hygiene Beaute'), ('Entretien, accessoires de maison', 'Entretien Accessoires De Maison'), ('Tout pour bébé', 'Tout Pour Bebe'), ('Animalerie', 'Animalerie'), ('Produits du monde', 'Produits Du Monde'), ('Bio et nutrition', 'Bio Et Nutrition')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Pommes_de_terre', 'Pommes De Terre'), ('Tomates', 'Tomates'), ('Bananes', 'Bananes'), ('Steaks haches', 'Steaks Haches'), ('Frites', 'Frites')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(choices=[('Auchan', 'Auchan'), ('Lidl', 'Lidl'), ('Carrefour', 'Carrefour'), ('E.Leclerc', 'E Leclerc'), ('Intermarché', 'Intermarche')], max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['rating'], name='store_store_rating_99a69e_idx'), models.Index(fields=['is_popular'], name='store_store_is_popu_3eb73d_idx')],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='shopstores',
            field=models.ManyToManyField(blank=True, related_name='categories_in_category', to='store.store'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_seasonal', models.CharField(default='False', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='store.product')),
                ('shopstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.store')),
            ],
            options={
                'ordering': ['-is_popular', 'name'],
                'indexes': [models.Index(fields=['is_seasonal'], name='store_artic_is_seas_e13cab_idx'), models.Index(fields=['is_popular'], name='store_artic_is_popu_dcc127_idx')],
            },
        ),
    ]
