# Generated by Django 5.0 on 2025-01-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='image_url',
            field=models.ImageField(blank=True, default='backend/statics/carrefour.png', null=True, upload_to='backend/statics/'),
        ),
    ]
