# Generated by Django 5.0 on 2025-01-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_address_alter_store_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image_url',
            field=models.CharField(default='/static/images/default_store.png', max_length=255),
        ),
    ]
