# Generated by Django 5.0 on 2025-01-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image_url',
            field=models.ImageField(default='images/stores/carrefour.png', upload_to='images/stores/'),
        ),
    ]
