# Generated by Django 5.0 on 2025-01-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store')),
            ],
            options={
                'ordering': ['-is_popular', 'name'],
                'indexes': [models.Index(fields=['is_seasonal'], name='product_pro_is_seas_d719b6_idx'), models.Index(fields=['is_popular'], name='product_pro_is_popu_fb10d8_idx'), models.Index(fields=['category'], name='product_pro_categor_0d8ef2_idx')],
            },
        ),
    ]
