# Generated by Django 5.0 on 2025-01-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='backend/statics/potatos.png', null=True, upload_to='backend/statics/'),
        ),
    ]
