# Generated by Django 5.0 on 2025-01-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='/static/images/default_product.png', max_length=255),
        ),
    ]
