# Generated by Django 5.1.5 on 2025-02-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, default='images/recipes/pate_carbo.png', null=True, upload_to='')),
                ('preparation_time', models.IntegerField(help_text='Time in minutes')),
                ('cooking_time', models.IntegerField(help_text='Time in minutes')),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
                ('instructions', models.TextField()),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='store.article')),
            ],
            options={
                'ordering': ['-is_popular', 'name'],
                'indexes': [models.Index(fields=['is_popular'], name='recipe_reci_is_popu_a351a3_idx'), models.Index(fields=['difficulty'], name='recipe_reci_difficu_800be8_idx')],
            },
        ),
    ]
