# Generated by Django 5.0 on 2025-01-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(blank=True, default='images/recipes/pate_carbo.png', null=True, upload_to=''),
        ),
    ]
